{% set name = "dtool_lookup_server_plugin_scaffolding" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool-lookup-server-plugin-scaffolding/dtool-lookup-server-plugin-scaffolding-{{ version }}.tar.gz
  sha256: b45e9adf0c9438f1290f22d6879bad6f159f42e931fac7894d923af9c2623b5d

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
  run:
    - dtool_lookup_server >=0.17.2
    - python >={{ python_min }}

test:
  imports:
    - dtool_lookup_server_plugin_scaffolding
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IMTEK-Simulation/dtool-lookup-server-plugin-scaffolding
  summary: This scaffolding serves as a minimal template for dtool lookup server plugin developments.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
